apiVersion: 1
datasources:
- name: KPI-Postgres
  type: postgres
  uid: kpi-postgres-datasource
  access: proxy
  url: 127.0.0.1:5432
  database: kpi_metrics
  user: kpi_user
  password: secure_password
  isDefault: false
  editable: true
  jsonData:
    sslmode: disable
    maxOpenConns: 10
    maxIdleConns: 2
    connMaxLifetime: 14400
